#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# # Get list of staged files, pass only those to format
# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
# echo $STAGED_FILES

# if [ -n "$STAGED_FILES" ]; then
#   npx prettier --write "$STAGED_FILES"
#   git add "$STAGED_FILES"
# fi

npm run format
git add .